# ------------------------------------------------------------
# Compiler + global settings
# ------------------------------------------------------------
CC          := gcc
SRC_DIR     := src
BUILD_DIR   := build
BIN_SERVER  := $(BUILD_DIR)/server/just-weather
BIN_CLIENT  := $(BUILD_DIR)/client/just-weather

# Compiler flags:
#  -std=c99 : C99 standard
#  -Wall -Wextra : warnings
#  -MMD -MP  : auto-generate dependency files
#  -Isrc/libs : include your project headers
#  -Isrc/jansson/src : include Jansson headers directly from its src folder
CFLAGS      := -Wall -Werror -Wfatal-errors -MMD -MP -Ilib/jansson -Isrc/lib -Isrc/server -Iincludes -g
JANSSON_CFLAGS := $(filter-out -Werror -Wfatal-errors,$(CFLAGS)) -w

# Linker flags and libraries
LDFLAGS     := -flto -Wl,--gc-sections
LIBS        := -lcurl


# ------------------------------------------------------------
# Source and object files
# ------------------------------------------------------------

# Find all project .c files under src/
SRC_SERVER := $(shell find -L $(SRC_DIR)/server -type f -name '*.c' ! -path "*/jansson/*") \
              $(shell find -L $(SRC_DIR)/lib -type f -name '*.c' ! -path "*/jansson/*")

SRC_CLIENT := $(shell find -L $(SRC_DIR)/client -type f -name '*.c' ! -path "*/jansson/*") \
              $(shell find -L $(SRC_DIR)/lib -type f -name '*.c' ! -path "*/jansson/*")

# Map each .c to a .o file in the build directory
OBJ_SERVER  := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRC_SERVER))
OBJ_CLIENT  := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRC_CLIENT))

# Dependency files generated by -MMD
DEP_SERVER  := $(OBJ_SERVER:.o=.d)
DEP_CLIENT  := $(OBJ_CLIENT:.o=.d)


# ------------------------------------------------------------
# Jansson integration
# ------------------------------------------------------------
# Only compile Jansson files inside lib/jansson/
JANSSON_SRC := $(shell find lib/jansson/ -maxdepth 1 -type f -name '*.c')
JANSSON_OBJ := $(patsubst lib/jansson/%.c,$(BUILD_DIR)/jansson/%.o,$(JANSSON_SRC))
OBJ_SERVER  += $(JANSSON_OBJ)
OBJ_CLIENT  += $(JANSSON_OBJ)


# ------------------------------------------------------------
# Build rules
# ------------------------------------------------------------

.PHONY: all
all: $(BIN_SERVER) $(BIN_CLIENT)
	@echo "Build complete."

$(BIN_SERVER): $(OBJ_SERVER)
	@$(CC) $(LDFLAGS) $(OBJ_SERVER) -o $@ $(LIBS)

$(BIN_CLIENT): $(OBJ_CLIENT)
	@$(CC) $(LDFLAGS) $(OBJ_CLIENT) -o $@ $(LIBS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	@echo "Compiling $<..."
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/jansson/%.o: lib/jansson/%.c
	@echo "Compiling Jansson $<..."
	@mkdir -p $(dir $@)
	@$(CC) $(JANSSON_CFLAGS) -c $< -o $@


# ------------------------------------------------------------
# Utilities
# ------------------------------------------------------------

.PHONY: run-server
run-server: $(BIN_SERVER)
	./$(BIN_SERVER)

.PHONY: run-client
run-client: $(BIN_CLIENT)
	./$(BIN_CLIENT)

.PHONY: clean
clean:
	@rm -rf $(BUILD_DIR) $(BIN_SERVER) $(BIN_CLIENT)

.PHONY: format
format:
	find . \( -name '*.c' -o -name '*.h' \) -print0 | xargs -0 clang-format -i -style=file


# ------------------------------------------------------------
# GitHub Actions (act)
# ------------------------------------------------------------

.PHONY: workflow-build
workflow-build:
	DOCKER_HOST="$${DOCKER_HOST}" act push --job build \
       -P ubuntu-latest=catthehacker/ubuntu:act-latest

.PHONY: workflow-format
workflow-format:
	DOCKER_HOST="$${DOCKER_HOST}" act push --job format-check \
       -P ubuntu-latest=teeks99/clang-ubuntu:19

.PHONY: workflow
workflow: workflow-build workflow-format


# ------------------------------------------------------------
# Dependencies
# ------------------------------------------------------------
-include $(DEP_SERVER)
-include $(DEP_CLIENT)

